// Code generated by ent, DO NOT EDIT.

package agent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/agentid-chain/agentid-chain/ent/predicate"
	"github.com/google/uuid"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldID, id))
}

// OwnerDid applies equality check predicate on the "owner_did" field. It's identical to OwnerDidEQ.
func OwnerDid(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldOwnerDid, v))
}

// Level applies equality check predicate on the "level" field. It's identical to LevelEQ.
func Level(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldLevel, v))
}

// Permission applies equality check predicate on the "permission" field. It's identical to PermissionEQ.
func Permission(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldPermission, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldStatus, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerDidEQ applies the EQ predicate on the "owner_did" field.
func OwnerDidEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldOwnerDid, v))
}

// OwnerDidNEQ applies the NEQ predicate on the "owner_did" field.
func OwnerDidNEQ(v string) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldOwnerDid, v))
}

// OwnerDidIn applies the In predicate on the "owner_did" field.
func OwnerDidIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldOwnerDid, vs...))
}

// OwnerDidNotIn applies the NotIn predicate on the "owner_did" field.
func OwnerDidNotIn(vs ...string) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldOwnerDid, vs...))
}

// OwnerDidGT applies the GT predicate on the "owner_did" field.
func OwnerDidGT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldOwnerDid, v))
}

// OwnerDidGTE applies the GTE predicate on the "owner_did" field.
func OwnerDidGTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldOwnerDid, v))
}

// OwnerDidLT applies the LT predicate on the "owner_did" field.
func OwnerDidLT(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldOwnerDid, v))
}

// OwnerDidLTE applies the LTE predicate on the "owner_did" field.
func OwnerDidLTE(v string) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldOwnerDid, v))
}

// OwnerDidContains applies the Contains predicate on the "owner_did" field.
func OwnerDidContains(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContains(FieldOwnerDid, v))
}

// OwnerDidHasPrefix applies the HasPrefix predicate on the "owner_did" field.
func OwnerDidHasPrefix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasPrefix(FieldOwnerDid, v))
}

// OwnerDidHasSuffix applies the HasSuffix predicate on the "owner_did" field.
func OwnerDidHasSuffix(v string) predicate.Agent {
	return predicate.Agent(sql.FieldHasSuffix(FieldOwnerDid, v))
}

// OwnerDidEqualFold applies the EqualFold predicate on the "owner_did" field.
func OwnerDidEqualFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldEqualFold(FieldOwnerDid, v))
}

// OwnerDidContainsFold applies the ContainsFold predicate on the "owner_did" field.
func OwnerDidContainsFold(v string) predicate.Agent {
	return predicate.Agent(sql.FieldContainsFold(FieldOwnerDid, v))
}

// LevelEQ applies the EQ predicate on the "level" field.
func LevelEQ(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldLevel, v))
}

// LevelNEQ applies the NEQ predicate on the "level" field.
func LevelNEQ(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldLevel, v))
}

// LevelIn applies the In predicate on the "level" field.
func LevelIn(vs ...uint8) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldLevel, vs...))
}

// LevelNotIn applies the NotIn predicate on the "level" field.
func LevelNotIn(vs ...uint8) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldLevel, vs...))
}

// LevelGT applies the GT predicate on the "level" field.
func LevelGT(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldLevel, v))
}

// LevelGTE applies the GTE predicate on the "level" field.
func LevelGTE(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldLevel, v))
}

// LevelLT applies the LT predicate on the "level" field.
func LevelLT(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldLevel, v))
}

// LevelLTE applies the LTE predicate on the "level" field.
func LevelLTE(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldLevel, v))
}

// PermissionEQ applies the EQ predicate on the "permission" field.
func PermissionEQ(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldPermission, v))
}

// PermissionNEQ applies the NEQ predicate on the "permission" field.
func PermissionNEQ(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldPermission, v))
}

// PermissionIn applies the In predicate on the "permission" field.
func PermissionIn(vs ...uint64) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldPermission, vs...))
}

// PermissionNotIn applies the NotIn predicate on the "permission" field.
func PermissionNotIn(vs ...uint64) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldPermission, vs...))
}

// PermissionGT applies the GT predicate on the "permission" field.
func PermissionGT(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldPermission, v))
}

// PermissionGTE applies the GTE predicate on the "permission" field.
func PermissionGTE(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldPermission, v))
}

// PermissionLT applies the LT predicate on the "permission" field.
func PermissionLT(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldPermission, v))
}

// PermissionLTE applies the LTE predicate on the "permission" field.
func PermissionLTE(v uint64) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldPermission, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...uint8) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...uint8) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v uint8) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Agent {
	return predicate.Agent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Agent) predicate.Agent {
	return predicate.Agent(sql.NotPredicates(p))
}
