apiVersion: v1
kind: Service
metadata:
  name: {{ include "agentid-chain.fullname" . }}
  labels:
    {{- include "agentid-chain.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
    - name: pprof
      port: {{ .Values.service.pprofPort }}
      targetPort: pprof
      protocol: TCP
  selector:
    {{- include "agentid-chain.selectorLabels" . | nindent 4 }}
