// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AgentsColumns holds the columns for the "agents" table.
	AgentsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "owner_did", Type: field.TypeString, Size: 256},
		{Name: "level", Type: field.TypeUint8, Default: 0},
		{Name: "permission", Type: field.TypeUint64, Default: 0},
		{Name: "status", Type: field.TypeUint8, Default: 0},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// AgentsTable holds the schema information for the "agents" table.
	AgentsTable = &schema.Table{
		Name:       "agents",
		Columns:    AgentsColumns,
		PrimaryKey: []*schema.Column{AgentsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idx_agent_owner_did",
				Unique:  false,
				Columns: []*schema.Column{AgentsColumns[1]},
			},
			{
				Name:    "idx_agent_status",
				Unique:  false,
				Columns: []*schema.Column{AgentsColumns[4]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "action", Type: field.TypeString, Size: 64},
		{Name: "reason", Type: field.TypeString, Nullable: true, Size: 1024},
		{Name: "operator_did", Type: field.TypeString, Size: 256},
		{Name: "occurred_at", Type: field.TypeTime},
		{Name: "agent_audit_logs", Type: field.TypeUUID},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "audit_logs_agents_audit_logs",
				Columns:    []*schema.Column{AuditLogsColumns[5]},
				RefColumns: []*schema.Column{AgentsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "email", Type: field.TypeString, Unique: true, Size: 320},
		{Name: "role_did", Type: field.TypeString, Size: 256},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AgentsTable,
		AuditLogsTable,
		UsersTable,
	}
)

func init() {
	AuditLogsTable.ForeignKeys[0].RefTable = AgentsTable
}
