// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentid-chain/agentid-chain/ent/agent"
	"github.com/agentid-chain/agentid-chain/ent/predicate"
)

// AgentUpdate is the builder for updating Agent entities.
type AgentUpdate struct {
	config
	hooks    []Hook
	mutation *AgentMutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdate) Where(ps ...predicate.Agent) *AgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerDid sets the "owner_did" field.
func (_u *AgentUpdate) SetOwnerDid(v string) *AgentUpdate {
	_u.mutation.SetOwnerDid(v)
	return _u
}

// SetNillableOwnerDid sets the "owner_did" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableOwnerDid(v *string) *AgentUpdate {
	if v != nil {
		_u.SetOwnerDid(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *AgentUpdate) SetLevel(v uint8) *AgentUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableLevel(v *uint8) *AgentUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *AgentUpdate) AddLevel(v int8) *AgentUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetPermission sets the "permission" field.
func (_u *AgentUpdate) SetPermission(v uint64) *AgentUpdate {
	_u.mutation.ResetPermission()
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *AgentUpdate) SetNillablePermission(v *uint64) *AgentUpdate {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// AddPermission adds value to the "permission" field.
func (_u *AgentUpdate) AddPermission(v int64) *AgentUpdate {
	_u.mutation.AddPermission(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdate) SetStatus(v uint8) *AgentUpdate {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdate) SetNillableStatus(v *uint8) *AgentUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AgentUpdate) AddStatus(v int8) *AgentUpdate {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdate) SetUpdatedAt(v time.Time) *AgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdate) Mutation() *AgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdate) check() error {
	if v, ok := _u.mutation.OwnerDid(); ok {
		if err := agent.OwnerDidValidator(v); err != nil {
			return &ValidationError{Name: "owner_did", err: fmt.Errorf(`ent: validator failed for field "Agent.owner_did": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := agent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Agent.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerDid(); ok {
		_spec.SetField(agent.FieldOwnerDid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(agent.FieldLevel, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(agent.FieldLevel, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(agent.FieldPermission, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedPermission(); ok {
		_spec.AddField(agent.FieldPermission, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AgentUpdateOne is the builder for updating a single Agent entity.
type AgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AgentMutation
}

// SetOwnerDid sets the "owner_did" field.
func (_u *AgentUpdateOne) SetOwnerDid(v string) *AgentUpdateOne {
	_u.mutation.SetOwnerDid(v)
	return _u
}

// SetNillableOwnerDid sets the "owner_did" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableOwnerDid(v *string) *AgentUpdateOne {
	if v != nil {
		_u.SetOwnerDid(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *AgentUpdateOne) SetLevel(v uint8) *AgentUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableLevel(v *uint8) *AgentUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *AgentUpdateOne) AddLevel(v int8) *AgentUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetPermission sets the "permission" field.
func (_u *AgentUpdateOne) SetPermission(v uint64) *AgentUpdateOne {
	_u.mutation.ResetPermission()
	_u.mutation.SetPermission(v)
	return _u
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillablePermission(v *uint64) *AgentUpdateOne {
	if v != nil {
		_u.SetPermission(*v)
	}
	return _u
}

// AddPermission adds value to the "permission" field.
func (_u *AgentUpdateOne) AddPermission(v int64) *AgentUpdateOne {
	_u.mutation.AddPermission(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *AgentUpdateOne) SetStatus(v uint8) *AgentUpdateOne {
	_u.mutation.ResetStatus()
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AgentUpdateOne) SetNillableStatus(v *uint8) *AgentUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// AddStatus adds value to the "status" field.
func (_u *AgentUpdateOne) AddStatus(v int8) *AgentUpdateOne {
	_u.mutation.AddStatus(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AgentUpdateOne) SetUpdatedAt(v time.Time) *AgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AgentMutation object of the builder.
func (_u *AgentUpdateOne) Mutation() *AgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the AgentUpdate builder.
func (_u *AgentUpdateOne) Where(ps ...predicate.Agent) *AgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AgentUpdateOne) Select(field string, fields ...string) *AgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Agent entity.
func (_u *AgentUpdateOne) Save(ctx context.Context) (*Agent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AgentUpdateOne) SaveX(ctx context.Context) *Agent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := agent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AgentUpdateOne) check() error {
	if v, ok := _u.mutation.OwnerDid(); ok {
		if err := agent.OwnerDidValidator(v); err != nil {
			return &ValidationError{Name: "owner_did", err: fmt.Errorf(`ent: validator failed for field "Agent.owner_did": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := agent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Agent.level": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	return nil
}

func (_u *AgentUpdateOne) sqlSave(ctx context.Context) (_node *Agent, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(agent.Table, agent.Columns, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Agent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, agent.FieldID)
		for _, f := range fields {
			if !agent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != agent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.OwnerDid(); ok {
		_spec.SetField(agent.FieldOwnerDid, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(agent.FieldLevel, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(agent.FieldLevel, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.Permission(); ok {
		_spec.SetField(agent.FieldPermission, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.AddedPermission(); ok {
		_spec.AddField(agent.FieldPermission, field.TypeUint64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.AddedStatus(); ok {
		_spec.AddField(agent.FieldStatus, field.TypeUint8, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &Agent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{agent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
