// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentid-chain/agentid-chain/ent/agent"
	"github.com/agentid-chain/agentid-chain/ent/auditlog"
	"github.com/google/uuid"
)

// AgentCreate is the builder for creating a Agent entity.
type AgentCreate struct {
	config
	mutation *AgentMutation
	hooks    []Hook
}

// SetOwnerDid sets the "owner_did" field.
func (_c *AgentCreate) SetOwnerDid(v string) *AgentCreate {
	_c.mutation.SetOwnerDid(v)
	return _c
}

// SetLevel sets the "level" field.
func (_c *AgentCreate) SetLevel(v uint8) *AgentCreate {
	_c.mutation.SetLevel(v)
	return _c
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_c *AgentCreate) SetNillableLevel(v *uint8) *AgentCreate {
	if v != nil {
		_c.SetLevel(*v)
	}
	return _c
}

// SetPermission sets the "permission" field.
func (_c *AgentCreate) SetPermission(v uint64) *AgentCreate {
	_c.mutation.SetPermission(v)
	return _c
}

// SetNillablePermission sets the "permission" field if the given value is not nil.
func (_c *AgentCreate) SetNillablePermission(v *uint64) *AgentCreate {
	if v != nil {
		_c.SetPermission(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *AgentCreate) SetStatus(v uint8) *AgentCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *AgentCreate) SetNillableStatus(v *uint8) *AgentCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *AgentCreate) SetCreatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableCreatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AgentCreate) SetUpdatedAt(v time.Time) *AgentCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AgentCreate) SetNillableUpdatedAt(v *time.Time) *AgentCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *AgentCreate) SetID(v uuid.UUID) *AgentCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *AgentCreate) SetNillableID(v *uuid.UUID) *AgentCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// AddAuditLogIDs adds the "audit_logs" edge to the AuditLog entity by IDs.
func (_c *AgentCreate) AddAuditLogIDs(ids ...uuid.UUID) *AgentCreate {
	_c.mutation.AddAuditLogIDs(ids...)
	return _c
}

// AddAuditLogs adds the "audit_logs" edges to the AuditLog entity.
func (_c *AgentCreate) AddAuditLogs(v ...*AuditLog) *AgentCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAuditLogIDs(ids...)
}

// Mutation returns the AgentMutation object of the builder.
func (_c *AgentCreate) Mutation() *AgentMutation {
	return _c.mutation
}

// Save creates the Agent in the database.
func (_c *AgentCreate) Save(ctx context.Context) (*Agent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AgentCreate) SaveX(ctx context.Context) *Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AgentCreate) defaults() {
	if _, ok := _c.mutation.Level(); !ok {
		v := agent.DefaultLevel
		_c.mutation.SetLevel(v)
	}
	if _, ok := _c.mutation.Permission(); !ok {
		v := agent.DefaultPermission
		_c.mutation.SetPermission(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := agent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := agent.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := agent.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := agent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AgentCreate) check() error {
	if _, ok := _c.mutation.OwnerDid(); !ok {
		return &ValidationError{Name: "owner_did", err: errors.New(`ent: missing required field "Agent.owner_did"`)}
	}
	if v, ok := _c.mutation.OwnerDid(); ok {
		if err := agent.OwnerDidValidator(v); err != nil {
			return &ValidationError{Name: "owner_did", err: fmt.Errorf(`ent: validator failed for field "Agent.owner_did": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Level(); !ok {
		return &ValidationError{Name: "level", err: errors.New(`ent: missing required field "Agent.level"`)}
	}
	if v, ok := _c.mutation.Level(); ok {
		if err := agent.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Agent.level": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Permission(); !ok {
		return &ValidationError{Name: "permission", err: errors.New(`ent: missing required field "Agent.permission"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "Agent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := agent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Agent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Agent.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Agent.updated_at"`)}
	}
	return nil
}

func (_c *AgentCreate) sqlSave(ctx context.Context) (*Agent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AgentCreate) createSpec() (*Agent, *sqlgraph.CreateSpec) {
	var (
		_node = &Agent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(agent.Table, sqlgraph.NewFieldSpec(agent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.OwnerDid(); ok {
		_spec.SetField(agent.FieldOwnerDid, field.TypeString, value)
		_node.OwnerDid = value
	}
	if value, ok := _c.mutation.Level(); ok {
		_spec.SetField(agent.FieldLevel, field.TypeUint8, value)
		_node.Level = value
	}
	if value, ok := _c.mutation.Permission(); ok {
		_spec.SetField(agent.FieldPermission, field.TypeUint64, value)
		_node.Permission = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(agent.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(agent.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(agent.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.AuditLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   agent.AuditLogsTable,
			Columns: []string{agent.AuditLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(auditlog.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AgentCreateBulk is the builder for creating many Agent entities in bulk.
type AgentCreateBulk struct {
	config
	err      error
	builders []*AgentCreate
}

// Save creates the Agent entities in the database.
func (_c *AgentCreateBulk) Save(ctx context.Context) ([]*Agent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Agent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AgentMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AgentCreateBulk) SaveX(ctx context.Context) []*Agent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AgentCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AgentCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
