// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/agentid-chain/agentid-chain/ent/outboxevent"
	"github.com/google/uuid"
)

// OutboxEventCreate is the builder for creating a OutboxEvent entity.
type OutboxEventCreate struct {
	config
	mutation *OutboxEventMutation
	hooks    []Hook
}

// SetAggregateType sets the "aggregate_type" field.
func (_c *OutboxEventCreate) SetAggregateType(v string) *OutboxEventCreate {
	_c.mutation.SetAggregateType(v)
	return _c
}

// SetAggregateID sets the "aggregate_id" field.
func (_c *OutboxEventCreate) SetAggregateID(v string) *OutboxEventCreate {
	_c.mutation.SetAggregateID(v)
	return _c
}

// SetEventType sets the "event_type" field.
func (_c *OutboxEventCreate) SetEventType(v string) *OutboxEventCreate {
	_c.mutation.SetEventType(v)
	return _c
}

// SetPayload sets the "payload" field.
func (_c *OutboxEventCreate) SetPayload(v map[string]interface{}) *OutboxEventCreate {
	_c.mutation.SetPayload(v)
	return _c
}

// SetOccurredAt sets the "occurred_at" field.
func (_c *OutboxEventCreate) SetOccurredAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetOccurredAt(v)
	return _c
}

// SetNillableOccurredAt sets the "occurred_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableOccurredAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetOccurredAt(*v)
	}
	return _c
}

// SetIdempotencyKey sets the "idempotency_key" field.
func (_c *OutboxEventCreate) SetIdempotencyKey(v string) *OutboxEventCreate {
	_c.mutation.SetIdempotencyKey(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *OutboxEventCreate) SetStatus(v uint8) *OutboxEventCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableStatus(v *uint8) *OutboxEventCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *OutboxEventCreate) SetRetryCount(v int) *OutboxEventCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableRetryCount(v *int) *OutboxEventCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetLastError sets the "last_error" field.
func (_c *OutboxEventCreate) SetLastError(v string) *OutboxEventCreate {
	_c.mutation.SetLastError(v)
	return _c
}

// SetNillableLastError sets the "last_error" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableLastError(v *string) *OutboxEventCreate {
	if v != nil {
		_c.SetLastError(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *OutboxEventCreate) SetNextRetryAt(v time.Time) *OutboxEventCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableNextRetryAt(v *time.Time) *OutboxEventCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *OutboxEventCreate) SetID(v uuid.UUID) *OutboxEventCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *OutboxEventCreate) SetNillableID(v *uuid.UUID) *OutboxEventCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// Mutation returns the OutboxEventMutation object of the builder.
func (_c *OutboxEventCreate) Mutation() *OutboxEventMutation {
	return _c.mutation
}

// Save creates the OutboxEvent in the database.
func (_c *OutboxEventCreate) Save(ctx context.Context) (*OutboxEvent, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *OutboxEventCreate) SaveX(ctx context.Context) *OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *OutboxEventCreate) defaults() {
	if _, ok := _c.mutation.OccurredAt(); !ok {
		v := outboxevent.DefaultOccurredAt()
		_c.mutation.SetOccurredAt(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := outboxevent.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := outboxevent.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.NextRetryAt(); !ok {
		v := outboxevent.DefaultNextRetryAt()
		_c.mutation.SetNextRetryAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := outboxevent.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *OutboxEventCreate) check() error {
	if _, ok := _c.mutation.AggregateType(); !ok {
		return &ValidationError{Name: "aggregate_type", err: errors.New(`ent: missing required field "OutboxEvent.aggregate_type"`)}
	}
	if v, ok := _c.mutation.AggregateType(); ok {
		if err := outboxevent.AggregateTypeValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AggregateID(); !ok {
		return &ValidationError{Name: "aggregate_id", err: errors.New(`ent: missing required field "OutboxEvent.aggregate_id"`)}
	}
	if v, ok := _c.mutation.AggregateID(); ok {
		if err := outboxevent.AggregateIDValidator(v); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.aggregate_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.EventType(); !ok {
		return &ValidationError{Name: "event_type", err: errors.New(`ent: missing required field "OutboxEvent.event_type"`)}
	}
	if v, ok := _c.mutation.EventType(); ok {
		if err := outboxevent.EventTypeValidator(v); err != nil {
			return &ValidationError{Name: "event_type", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.event_type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Payload(); !ok {
		return &ValidationError{Name: "payload", err: errors.New(`ent: missing required field "OutboxEvent.payload"`)}
	}
	if _, ok := _c.mutation.OccurredAt(); !ok {
		return &ValidationError{Name: "occurred_at", err: errors.New(`ent: missing required field "OutboxEvent.occurred_at"`)}
	}
	if _, ok := _c.mutation.IdempotencyKey(); !ok {
		return &ValidationError{Name: "idempotency_key", err: errors.New(`ent: missing required field "OutboxEvent.idempotency_key"`)}
	}
	if v, ok := _c.mutation.IdempotencyKey(); ok {
		if err := outboxevent.IdempotencyKeyValidator(v); err != nil {
			return &ValidationError{Name: "idempotency_key", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.idempotency_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "OutboxEvent.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := outboxevent.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "OutboxEvent.retry_count"`)}
	}
	if v, ok := _c.mutation.LastError(); ok {
		if err := outboxevent.LastErrorValidator(v); err != nil {
			return &ValidationError{Name: "last_error", err: fmt.Errorf(`ent: validator failed for field "OutboxEvent.last_error": %w`, err)}
		}
	}
	if _, ok := _c.mutation.NextRetryAt(); !ok {
		return &ValidationError{Name: "next_retry_at", err: errors.New(`ent: missing required field "OutboxEvent.next_retry_at"`)}
	}
	return nil
}

func (_c *OutboxEventCreate) sqlSave(ctx context.Context) (*OutboxEvent, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *OutboxEventCreate) createSpec() (*OutboxEvent, *sqlgraph.CreateSpec) {
	var (
		_node = &OutboxEvent{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(outboxevent.Table, sqlgraph.NewFieldSpec(outboxevent.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.AggregateType(); ok {
		_spec.SetField(outboxevent.FieldAggregateType, field.TypeString, value)
		_node.AggregateType = value
	}
	if value, ok := _c.mutation.AggregateID(); ok {
		_spec.SetField(outboxevent.FieldAggregateID, field.TypeString, value)
		_node.AggregateID = value
	}
	if value, ok := _c.mutation.EventType(); ok {
		_spec.SetField(outboxevent.FieldEventType, field.TypeString, value)
		_node.EventType = value
	}
	if value, ok := _c.mutation.Payload(); ok {
		_spec.SetField(outboxevent.FieldPayload, field.TypeJSON, value)
		_node.Payload = value
	}
	if value, ok := _c.mutation.OccurredAt(); ok {
		_spec.SetField(outboxevent.FieldOccurredAt, field.TypeTime, value)
		_node.OccurredAt = value
	}
	if value, ok := _c.mutation.IdempotencyKey(); ok {
		_spec.SetField(outboxevent.FieldIdempotencyKey, field.TypeString, value)
		_node.IdempotencyKey = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(outboxevent.FieldStatus, field.TypeUint8, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(outboxevent.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.LastError(); ok {
		_spec.SetField(outboxevent.FieldLastError, field.TypeString, value)
		_node.LastError = value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(outboxevent.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = value
	}
	return _node, _spec
}

// OutboxEventCreateBulk is the builder for creating many OutboxEvent entities in bulk.
type OutboxEventCreateBulk struct {
	config
	err      error
	builders []*OutboxEventCreate
}

// Save creates the OutboxEvent entities in the database.
func (_c *OutboxEventCreateBulk) Save(ctx context.Context) ([]*OutboxEvent, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*OutboxEvent, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*OutboxEventMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) SaveX(ctx context.Context) []*OutboxEvent {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *OutboxEventCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *OutboxEventCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
