// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/agentid-chain/agentid-chain/ent/agent"
	"github.com/agentid-chain/agentid-chain/ent/auditlog"
	"github.com/agentid-chain/agentid-chain/ent/outboxevent"
	"github.com/agentid-chain/agentid-chain/ent/schema"
	"github.com/agentid-chain/agentid-chain/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescOwnerDid is the schema descriptor for owner_did field.
	agentDescOwnerDid := agentFields[1].Descriptor()
	// agent.OwnerDidValidator is a validator for the "owner_did" field. It is called by the builders before save.
	agent.OwnerDidValidator = func() func(string) error {
		validators := agentDescOwnerDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(owner_did string) error {
			for _, fn := range fns {
				if err := fn(owner_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// agentDescLevel is the schema descriptor for level field.
	agentDescLevel := agentFields[2].Descriptor()
	// agent.DefaultLevel holds the default value on creation for the level field.
	agent.DefaultLevel = agentDescLevel.Default.(uint8)
	// agent.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	agent.LevelValidator = agentDescLevel.Validators[0].(func(uint8) error)
	// agentDescPermission is the schema descriptor for permission field.
	agentDescPermission := agentFields[3].Descriptor()
	// agent.DefaultPermission holds the default value on creation for the permission field.
	agent.DefaultPermission = agentDescPermission.Default.(uint64)
	// agentDescStatus is the schema descriptor for status field.
	agentDescStatus := agentFields[4].Descriptor()
	// agent.DefaultStatus holds the default value on creation for the status field.
	agent.DefaultStatus = agentDescStatus.Default.(uint8)
	// agent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agent.StatusValidator = agentDescStatus.Validators[0].(func(uint8) error)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[5].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentFields[6].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = func() func(string) error {
		validators := auditlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditlogDescReason is the schema descriptor for reason field.
	auditlogDescReason := auditlogFields[2].Descriptor()
	// auditlog.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	auditlog.ReasonValidator = auditlogDescReason.Validators[0].(func(string) error)
	// auditlogDescOperatorDid is the schema descriptor for operator_did field.
	auditlogDescOperatorDid := auditlogFields[3].Descriptor()
	// auditlog.OperatorDidValidator is a validator for the "operator_did" field. It is called by the builders before save.
	auditlog.OperatorDidValidator = func() func(string) error {
		validators := auditlogDescOperatorDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(operator_did string) error {
			for _, fn := range fns {
				if err := fn(operator_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditlogDescOccurredAt is the schema descriptor for occurred_at field.
	auditlogDescOccurredAt := auditlogFields[4].Descriptor()
	// auditlog.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	auditlog.DefaultOccurredAt = auditlogDescOccurredAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	outboxeventFields := schema.OutboxEvent{}.Fields()
	_ = outboxeventFields
	// outboxeventDescAggregateType is the schema descriptor for aggregate_type field.
	outboxeventDescAggregateType := outboxeventFields[1].Descriptor()
	// outboxevent.AggregateTypeValidator is a validator for the "aggregate_type" field. It is called by the builders before save.
	outboxevent.AggregateTypeValidator = func() func(string) error {
		validators := outboxeventDescAggregateType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(aggregate_type string) error {
			for _, fn := range fns {
				if err := fn(aggregate_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// outboxeventDescAggregateID is the schema descriptor for aggregate_id field.
	outboxeventDescAggregateID := outboxeventFields[2].Descriptor()
	// outboxevent.AggregateIDValidator is a validator for the "aggregate_id" field. It is called by the builders before save.
	outboxevent.AggregateIDValidator = func() func(string) error {
		validators := outboxeventDescAggregateID.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(aggregate_id string) error {
			for _, fn := range fns {
				if err := fn(aggregate_id); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// outboxeventDescEventType is the schema descriptor for event_type field.
	outboxeventDescEventType := outboxeventFields[3].Descriptor()
	// outboxevent.EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	outboxevent.EventTypeValidator = func() func(string) error {
		validators := outboxeventDescEventType.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(event_type string) error {
			for _, fn := range fns {
				if err := fn(event_type); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// outboxeventDescOccurredAt is the schema descriptor for occurred_at field.
	outboxeventDescOccurredAt := outboxeventFields[5].Descriptor()
	// outboxevent.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	outboxevent.DefaultOccurredAt = outboxeventDescOccurredAt.Default.(func() time.Time)
	// outboxeventDescIdempotencyKey is the schema descriptor for idempotency_key field.
	outboxeventDescIdempotencyKey := outboxeventFields[6].Descriptor()
	// outboxevent.IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	outboxevent.IdempotencyKeyValidator = func() func(string) error {
		validators := outboxeventDescIdempotencyKey.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(idempotency_key string) error {
			for _, fn := range fns {
				if err := fn(idempotency_key); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// outboxeventDescStatus is the schema descriptor for status field.
	outboxeventDescStatus := outboxeventFields[7].Descriptor()
	// outboxevent.DefaultStatus holds the default value on creation for the status field.
	outboxevent.DefaultStatus = outboxeventDescStatus.Default.(uint8)
	// outboxevent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	outboxevent.StatusValidator = outboxeventDescStatus.Validators[0].(func(uint8) error)
	// outboxeventDescRetryCount is the schema descriptor for retry_count field.
	outboxeventDescRetryCount := outboxeventFields[8].Descriptor()
	// outboxevent.DefaultRetryCount holds the default value on creation for the retry_count field.
	outboxevent.DefaultRetryCount = outboxeventDescRetryCount.Default.(int)
	// outboxeventDescLastError is the schema descriptor for last_error field.
	outboxeventDescLastError := outboxeventFields[9].Descriptor()
	// outboxevent.LastErrorValidator is a validator for the "last_error" field. It is called by the builders before save.
	outboxevent.LastErrorValidator = outboxeventDescLastError.Validators[0].(func(string) error)
	// outboxeventDescNextRetryAt is the schema descriptor for next_retry_at field.
	outboxeventDescNextRetryAt := outboxeventFields[10].Descriptor()
	// outboxevent.DefaultNextRetryAt holds the default value on creation for the next_retry_at field.
	outboxevent.DefaultNextRetryAt = outboxeventDescNextRetryAt.Default.(func() time.Time)
	// outboxeventDescID is the schema descriptor for id field.
	outboxeventDescID := outboxeventFields[0].Descriptor()
	// outboxevent.DefaultID holds the default value on creation for the id field.
	outboxevent.DefaultID = outboxeventDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRoleDid is the schema descriptor for role_did field.
	userDescRoleDid := userFields[2].Descriptor()
	// user.RoleDidValidator is a validator for the "role_did" field. It is called by the builders before save.
	user.RoleDidValidator = func() func(string) error {
		validators := userDescRoleDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(role_did string) error {
			for _, fn := range fns {
				if err := fn(role_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
