// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/agentid-chain/agentid-chain/ent/agent"
	"github.com/agentid-chain/agentid-chain/ent/auditlog"
	"github.com/agentid-chain/agentid-chain/ent/schema"
	"github.com/agentid-chain/agentid-chain/ent/user"
	"github.com/google/uuid"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentFields := schema.Agent{}.Fields()
	_ = agentFields
	// agentDescOwnerDid is the schema descriptor for owner_did field.
	agentDescOwnerDid := agentFields[1].Descriptor()
	// agent.OwnerDidValidator is a validator for the "owner_did" field. It is called by the builders before save.
	agent.OwnerDidValidator = func() func(string) error {
		validators := agentDescOwnerDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(owner_did string) error {
			for _, fn := range fns {
				if err := fn(owner_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// agentDescLevel is the schema descriptor for level field.
	agentDescLevel := agentFields[2].Descriptor()
	// agent.DefaultLevel holds the default value on creation for the level field.
	agent.DefaultLevel = agentDescLevel.Default.(uint8)
	// agent.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	agent.LevelValidator = agentDescLevel.Validators[0].(func(uint8) error)
	// agentDescPermission is the schema descriptor for permission field.
	agentDescPermission := agentFields[3].Descriptor()
	// agent.DefaultPermission holds the default value on creation for the permission field.
	agent.DefaultPermission = agentDescPermission.Default.(uint64)
	// agentDescStatus is the schema descriptor for status field.
	agentDescStatus := agentFields[4].Descriptor()
	// agent.DefaultStatus holds the default value on creation for the status field.
	agent.DefaultStatus = agentDescStatus.Default.(uint8)
	// agent.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	agent.StatusValidator = agentDescStatus.Validators[0].(func(uint8) error)
	// agentDescCreatedAt is the schema descriptor for created_at field.
	agentDescCreatedAt := agentFields[5].Descriptor()
	// agent.DefaultCreatedAt holds the default value on creation for the created_at field.
	agent.DefaultCreatedAt = agentDescCreatedAt.Default.(func() time.Time)
	// agentDescUpdatedAt is the schema descriptor for updated_at field.
	agentDescUpdatedAt := agentFields[6].Descriptor()
	// agent.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	agent.DefaultUpdatedAt = agentDescUpdatedAt.Default.(func() time.Time)
	// agent.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	agent.UpdateDefaultUpdatedAt = agentDescUpdatedAt.UpdateDefault.(func() time.Time)
	// agentDescID is the schema descriptor for id field.
	agentDescID := agentFields[0].Descriptor()
	// agent.DefaultID holds the default value on creation for the id field.
	agent.DefaultID = agentDescID.Default.(func() uuid.UUID)
	auditlogFields := schema.AuditLog{}.Fields()
	_ = auditlogFields
	// auditlogDescAction is the schema descriptor for action field.
	auditlogDescAction := auditlogFields[1].Descriptor()
	// auditlog.ActionValidator is a validator for the "action" field. It is called by the builders before save.
	auditlog.ActionValidator = func() func(string) error {
		validators := auditlogDescAction.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(action string) error {
			for _, fn := range fns {
				if err := fn(action); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditlogDescReason is the schema descriptor for reason field.
	auditlogDescReason := auditlogFields[2].Descriptor()
	// auditlog.ReasonValidator is a validator for the "reason" field. It is called by the builders before save.
	auditlog.ReasonValidator = auditlogDescReason.Validators[0].(func(string) error)
	// auditlogDescOperatorDid is the schema descriptor for operator_did field.
	auditlogDescOperatorDid := auditlogFields[3].Descriptor()
	// auditlog.OperatorDidValidator is a validator for the "operator_did" field. It is called by the builders before save.
	auditlog.OperatorDidValidator = func() func(string) error {
		validators := auditlogDescOperatorDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(operator_did string) error {
			for _, fn := range fns {
				if err := fn(operator_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// auditlogDescOccurredAt is the schema descriptor for occurred_at field.
	auditlogDescOccurredAt := auditlogFields[4].Descriptor()
	// auditlog.DefaultOccurredAt holds the default value on creation for the occurred_at field.
	auditlog.DefaultOccurredAt = auditlogDescOccurredAt.Default.(func() time.Time)
	// auditlogDescID is the schema descriptor for id field.
	auditlogDescID := auditlogFields[0].Descriptor()
	// auditlog.DefaultID holds the default value on creation for the id field.
	auditlog.DefaultID = auditlogDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[1].Descriptor()
	// user.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	user.EmailValidator = func() func(string) error {
		validators := userDescEmail.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(email string) error {
			for _, fn := range fns {
				if err := fn(email); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescRoleDid is the schema descriptor for role_did field.
	userDescRoleDid := userFields[2].Descriptor()
	// user.RoleDidValidator is a validator for the "role_did" field. It is called by the builders before save.
	user.RoleDidValidator = func() func(string) error {
		validators := userDescRoleDid.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(role_did string) error {
			for _, fn := range fns {
				if err := fn(role_did); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[3].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[4].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
